services:
  dst-master:
    build: .
    container_name: dst-master
    restart: unless-stopped
    ports:
      - "10999:10999/udp"
      - "10888:10888/udp" # Inter-shard communication
      - "27016:27016/udp" # Steam master server port
      - "8766:8766/udp"   # Steam authentication port
    env_file: .env
    environment:
      - SHARD_NAME=Master
      - SKIP_UPDATE=false
    volumes:
      - ./dst-data:/data
      - ./dedicated_server_mods_setup.lua:/opt/dst_server/mods/dedicated_server_mods_setup.lua
      - dst-bin:/opt/dst_server

  dst-caves:
    build: .
    container_name: dst-caves
    restart: unless-stopped
    depends_on:
      - dst-master
    ports:
      - "11000:11000/udp"
      - "27017:27017/udp" # Steam master server port
      - "8767:8767/udp"   # Steam authentication port
    env_file: .env
    environment:
      - SHARD_NAME=Caves
      - SKIP_UPDATE=true
    volumes:
      - ./dst-data:/data
      - ./dedicated_server_mods_setup.lua:/opt/dst_server/mods/dedicated_server_mods_setup.lua
      - dst-bin:/opt/dst_server

volumes:
  dst-bin:
